import type { Workspace } from "../shared/domain";
const createdAt = "2026-09-14T08:00:00Z";
export const demo: Workspace = {
  vessels: [
    {
      id: "demo-v1",
      name: "Atlantic Pioneer",
      imo: "9321483",
      type: "Container ship",
      flag: "Panama",
      capacity: 24,
      status: "At sea",
      destination: "Rotterdam, Netherlands",
      version: 1,
      createdAt,
    },
    {
      id: "demo-v2",
      name: "Pacific Endeavour",
      imo: "9319466",
      type: "Bulk carrier",
      flag: "Singapore",
      capacity: 22,
      status: "At sea",
      destination: "Singapore",
      version: 1,
      createdAt,
    },
    {
      id: "demo-v3",
      name: "Northern Horizon",
      imo: "9234563",
      type: "Tanker",
      flag: "Liberia",
      capacity: 20,
      status: "In port",
      destination: "Lagos, Nigeria",
      version: 1,
      createdAt,
    },
    {
      id: "demo-v4",
      name: "Coral Voyager",
      imo: "9387425",
      type: "Offshore vessel",
      flag: "Marshall Islands",
      capacity: 16,
      status: "Maintenance",
      destination: "Dubai, UAE",
      version: 1,
      createdAt,
    },
  ],
  crew: [
    {
      id: "demo-c1",
      name: "Alexander Morgan",
      email: "alexander@example.com",
      rank: "Captain",
      nationality: "United Kingdom",
      certificateExpiry: "2027-04-12",
      vesselId: "demo-v1",
      version: 1,
      createdAt,
    },
    {
      id: "demo-c2",
      name: "Isabella Santos",
      email: "isabella@example.com",
      rank: "Chief officer",
      nationality: "Philippines",
      certificateExpiry: "2026-09-28",
      vesselId: "demo-v1",
      version: 1,
      createdAt,
    },
    {
      id: "demo-c3",
      name: "Daniel Okafor",
      email: "daniel@example.com",
      rank: "Chief engineer",
      nationality: "Nigeria",
      certificateExpiry: "2027-02-18",
      vesselId: "demo-v2",
      version: 1,
      createdAt,
    },
    {
      id: "demo-c4",
      name: "James Wilson",
      email: "james@example.com",
      rank: "Second officer",
      nationality: "United Kingdom",
      certificateExpiry: "2026-09-21",
      vesselId: null,
      version: 1,
      createdAt,
    },
    {
      id: "demo-c5",
      name: "Maria Reyes",
      email: "maria@example.com",
      rank: "Second engineer",
      nationality: "Philippines",
      certificateExpiry: "2026-08-20",
      vesselId: "demo-v3",
      version: 1,
      createdAt,
    },
    {
      id: "demo-c6",
      name: "Samuel Adeyemi",
      email: "samuel@example.com",
      rank: "Able seafarer",
      nationality: "Nigeria",
      certificateExpiry: "2027-06-05",
      vesselId: null,
      version: 1,
      createdAt,
    },
  ],
  activity: [
    {
      id: "a1",
      message: "Crew member assigned · Isabella Santos → Atlantic Pioneer",
      createdAt: "2026-09-14T09:42:00Z",
    },
    {
      id: "a2",
      message: "Vessel status updated · Northern Horizon is in port",
      createdAt: "2026-09-14T08:20:00Z",
    },
    {
      id: "a3",
      message: "Crew member added · Samuel Adeyemi",
      createdAt: "2026-09-13T16:15:00Z",
    },
  ],
};
